routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\FrontTableCTRL;
use App\Http\Controllers\SearchFront;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::resource('search',SearchFront::class);
Route::get('/', [SearchFront::class,'search']);
Route::get('search', [SearchFront::class, 'search'])->name('search');


Route::get('front/PendingArchives',[FrontTableCTRL::class,'PendingArchives'])->name('PendingArchives');
Route::put('front/PendingArchives/{id}',[FrontTableCTRL::class,'PendingArchivesStore'])->name('PendingArchivesStore');
Route::delete('front/PendingArchives/{id}',[FrontTableCTRL::class,'PendingArchivesDestroy'])->name('PendingArchivesDestroy');
Route::resource('front',FrontTableCTRL::class);

app/Models/FrontTableModel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class FrontTableModel extends Model
{
    use HasFactory,SoftDeletes;

    
    protected $table = 'pending_t_b_l_s';
    protected $fillable = [ 
                            'case_no',
                            'school', 
                            'complainantfname', 
                            'complainantmname', 
                            'complainantlname', 
                            'complainantsuffix', 
                            'respondentfname', 
                            'respondentmname', 
                            'respondentlname',
                            'respondentsuffix',
                            'charges', 
                            'dateofactions',
                            'actions',
                            'status',
                          ];                  
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/FrontTableCTRL.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\FrontTableModel;
use Illuminate\Validation\Rule;

class FrontTableCTRL extends Controller
{
    public function index(){

        $pendings = FrontTableModel::orderBy('case_no')->get();
        return view('TableFront.FrontTable', ['pendings' => $pendings]);
    }

    public function create(){
        return view('TableFront.FrontTableAdd'); //Testing Comment 2

    }

    public function store(Request $request){
 
        $this->validate($request,[
            'case_no'=>['required',Rule::unique('pending_t_b_l_s', 'case_no')],
            'school' => 'required',
            'complainantfname' => 'required',
            'complainantlname' => 'required',
            'respondentfname' => 'required',
            'respondentlname' => 'required',
            'charges' => 'required',
            'dateofactions' => 'required',
            'actions' => 'required',
            'status' => 'required',
        ]);
    
        $input = $request->all(); 
        FrontTableModel::create($input); 
        
        return back()->with('successAdd','Case Added Successfully !');
    }

    public function edit($id){

        $pendings = FrontTableModel::findorFail($id);

        return view('TableFront.FrontTableUpdate', ['pendings'=>$pendings]);

    }
    public function update(Request $request, $id){
    
        $pendings = FrontTableModel::findorFail($id);
       
        $this->validate($request,[
          'case_no'=>['required',Rule::unique('pending_t_b_l_s', 'case_no')->ignore($pendings->id)],
          'school' => 'required',
          'complainantfname' => 'required',
          'complainantlname' => 'required',
          'respondentfname' => 'required',
          'respondentlname' => 'required',
          'charges' => 'required',
          'dateofactions' => 'required',
          'actions' => 'required',
          'status' => 'required',
        ]);
       
        $input = $request->all();
        $pendings->update($input);
  
        return back()->with('successupd','Case Has Been Updated !');   
    
    }
  
    public function destroy($id){
        
        FrontTableModel::findorFail($id)->delete();
        return back()->with('successdel',"Charges Has Been Move To Archives !");
    }

    public function PendingArchives(){
        
        $pendings = FrontTableModel::orderBy('case_no')->onlyTrashed()->get();
        return view('TableFront.FrontTableArchives', ['pendings' => $pendings ]);
    }

    public function PendingArchivesDestroy($id){
        
        FrontTableModel::onlyTrashed()->findorfail($id)->forcedelete();
        return back()->with('successdel',"This Case Has Been Deleted Pemanently !");
    }
    
    public function PendingArchivesStore($id){
        
        FrontTableModel::onlyTrashed()->findorfail($id)->restore();
        return back()->with('restor',"This Case Has Restore Successfully !");
    }

    public function show($id){
        $pendings = FrontTableModel::findorfail($id);
        return view('TableFront.FrontTableView', ['pendings' => $pendings]);
    }

}

app/Http/Controllers/SearchFront.php
<?php

namespace App\Http\Controllers;
use App\Models\FrontTableModel;
use Illuminate\Http\Request;

class SearchFront extends Controller
{
    public function search(Request $request){
   
        $search = $request->input('search');
    
        $posts = FrontTableModel::query()
            ->where('complainantfname', 'LIKE', "%{$search}%")
            ->orWhere('complainantlname', 'LIKE', "%{$search}%")
            ->orWhere('respondentfname', 'LIKE', "%{$search}%")
            ->orWhere('respondentlname', 'LIKE', "%{$search}%")
            ->get();
    
      
        $tbls = FrontTableModel::get();

        return view('YouSearch', ['posts'=>$posts, 'tbls' => $tbls]);
    }

    public function show($id){
        $pendings = FrontTableModel::findorFail($id);

        return view('TableFront.SearchRes', ['pendings'=>$pendings]);

    }

}

resources/views/Layout/Layout.blade.php
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> LEGAL </title>


    <link rel="stylesheet" href="{{ asset('css/Overview.css')}}">
    <link rel="icon" href="{{asset('/AssetsIMG/male.svg')}}" type="image/x-icon">
    <link rel="stylesheet" href="{{ asset('css/TableM.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link rel="stylesheet" href="{{ asset('css/Specifications.css')}}">
    <link rel="stylesheet" href="{{ asset('css/Toasted.css')}}">
    @yield('css')
 
  </head>
<body>

    <div class="main"> 

        {{-- @include('Layout.Navigation') --}}
        @yield('contents')
    
    </div>

    <script src="{{asset('js/SweetAlert.JS')}}"></script>
    <script src="{{asset('js/TBLS.JS')}}"></script>
    <script src="{{asset('js/TBLM.JS')}}"></script>
    <script src="{{asset('js/Connection.JS')}}"></script>
    <script src="{{asset('js/Preview.JS')}}"></script>
    <script src="{{asset('js/Toasted.JS')}}"></script>
    <script src="{{asset('js/Sweet.JS')}}"></script>

     

    <script>

        const Toast = Swal.mixin({           
                toast: true,
                position: 'top-end',
                showConfirmButton: false,
                timer: 3000,
                width: 350,
                showCloseButton: true,
                timerProgressBar: true,
                didOpen: (toast) => {
                toast.addEventListener('mouseenter', Swal.stopTimer)
                toast.addEventListener('mouseleave', Swal.resumeTimer)
                }
        })
      
      @if(Session::has('successAdd'))     
              
                Toast.fire({
                icon: 'success',
                title: '{{session('successAdd')}}'
        })
            
      @endif
      @if(Session::has('successdel'))  

                Swal.fire(
                   'Deleted!',
                   '{{session('successdel')}}',
                   'success'
                )
      @endif

      @if(Session::has('herror')) 
      
      Toast.fire({
              icon: 'error',
              title: '{{session('herror')}}'
      })
      @endif


      @if(Session::has('successban')) 
      
      Swal.fire(
              'Suspended !',
              '{{session('successban')}}',
              'success'
      ) 
      @endif

      @if(Session::has('successupd')) 
      
                Swal.fire(
                        'Upadated !',
                        '{{session('successupd')}}',
                        'success'
                ) 
      @endif

      @if(Session::has('restor')) 
      
                Swal.fire(
                        'Restored !',
                        '{{session('restor')}}',
                        'success'
                ) 
      @endif

      @if($errors->any())     
                Toast.fire({
                        icon: 'error',
                        title: 'Some Fields Are Empty !'
                })
      @endif
      
      
      @if(Session::has('errorss')) 
      
      Toast.fire({
              icon: 'warning',
              title: '{{session('errorss')}}'
      })

      @endif
      

        @if(Session::has('Log')) 
      
        Toast.fire({
                icon: 'success',
                title: '{{session('Log')}}'
        })

        @endif
    
        @if(Session::has('Cannot')) 

   
         Swal.fire({
          icon: 'error',
          title: 'Cannot Be Deleted',
          html: '{{session('Cannot')}}',
          backdrop: `
                rgba(0,0,123,0.4)
                url("/AssetsIMG/nyan.gif")
                left top
                no-repeat
                 `
          })
      

        @endif
  
      </script>
   

</body>

resources/views/Layout/Navigation.blade.php
<div class="cards">
    <a  href="{{route('front.index')}}" class="card" id="{{ Request::is('front') 
                                                         || Request::is('/')
                                                         || Request::is('front/create')
                                                         || Request::is('front/*/edit')
                                                         || Request::is('front/*')
                                                         || Request::is('front/PendingArchives') ? 'activecard' : ''}}">
        <div class="card-content">
            <div class="number">@yield('front')</div>
            <div class="card-name">Pending Investigation</div>
        </div>
        <div class="icon-box">
            <i class="fa-solid fa-bars-progress"></i>
        </div>
    </a>
    <a href="{{route('charges.index')}}" class="card" id="{{ Request::is('charges')
                                                          || Request::is('charges/create') 
                                                          || Request::is('charges/*/edit') ? 'activecard' : ''}}">
        <div class="card-content">
            <div class="number">@yield('charges')</div>
            <div class="card-name">Charges</div>
        </div>
        <div class="icon-box">
            <i class="fa-solid fa-file-signature"></i>
        </div>
    </a>
    <a href="{{route('actions.index')}}" class="card" id="{{ Request::is('actions')
                                                          || Request::is('actions/create') 
                                                          || Request::is('actions/*/edit') ? 'activecard' : ''}}">
        <div class="card-content">
            <div class="number">@yield('actions')</div>
            <div class="card-name">Actions </div>
        </div>
        <div class="icon-box">
            <i class="fa-regular fa-newspaper"></i>
        </div>
    </a>
    <a href="{{route('status.index')}}" class="card" id="{{ Request::is('status')
                                                         || Request::is('status/create') 
                                                         || Request::is('status/*/edit')? 'activecard' : ''}}">
        <div class="card-content">
            <div class="number">@yield('status')</div>
            <div class="card-name">Status</div>
        </div>
        <div class="icon-box">
            <i class="fa-solid fa-list-check"></i>
        </div>
    </a>

resources/views/TableFront/FrontTable.blade.php
@extends('Layout.Layout')

@section('front')
    {{$pendings->count()}}
@endsection

@section('contents')

    
<div  class = "M-Table">
    <div class="Table-1" >
        <div class="Table-con">
            <div class="Cnt">
                <H3 class="ORP">PENDING INVESTIGATION</H3>
                <p class="DY">Legal and Investigation Section</p>
            </div>
            <div class="Cnt2">                       
                <div class = "A-DD">
                    <a  href="{{route('PendingArchives')}}" class ="ARCC">  <i class="fa-solid fa-box-archive"></i></a> 
                </div> 
                <div class = "A-DD">
                    <a  href="{{route('front.create')}}" class ="Add-P">  <i class="fa-solid fa-plus"></i> <span> New </span></a>
                </div>                   
            </div> 
        </div>


        <div class = " Table-Section">
            <table id="Papers" class="display" style="width:100%">
                <thead>
                    <tr>
                        <th>CASE NO.</th> 
                        <th>SCHOOL</th>             
                        <th>COMPLAINANT</th>
                        <th>RESPONDENT</th>
                        <th>ACTIONS</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach($pendings as $pending)
                        <tr>
                            <td>{{$pending->case_no}}</td>
                            <td>{{$pending->school}}</td>
                            <td>{{$pending->complainantfname}} {{$pending->complainantmname}} {{$pending->complainantlname}} {{$pending->complainantsuffix}}</td>
                            <td>{{$pending->respondentfname}} {{$pending->respondentmname}} {{$pending->respondentlname}} {{$pending->respondentsuffix}}</td>                        
                            <td class="BTNS-EDTY">       
                                <a class="EditsT" href ="{{route('front.show',$pending->id)}}" > <i class="fa-solid fa-eye"></i> <span> VIEW </span>  </a>      
                                <a class="Edits" href ="{{route('front.edit',$pending->id)}}" > <i class="fa-solid fa-pen-to-square"></i>  <span> EDIT </span>  </a>  
                                <button class="Dlts"  onclick="deleteData({{$pending->id}})" type="submit"><i class="fa-solid fa-trash"></i>  <span> ARCHIVE </span>   </button>                      
                                <form id ="delete-form-{{$pending->id}}" action="{{Route('front.destroy', $pending->id)}}"  method = "POST">  @csrf @method('DELETE')  </form>  
                            </td>
                        </tr>
                     @endforeach
                </tbody>
            </table>          
        </div>                  
    </div>
</div>


  
@endsection

resources/views/TableFront/FrontTableAdd.blade.php
@extends('Layout.Layout')

@section('css')
    <link rel="stylesheet" href="{{ asset('css/AddingCss.css')}}">
@endsection

@section('contents')

<div class="main"> 
    <div class="Add-Holder"> 
        <div class="Add-InP"> 

            <div class ="Top-Form">
                <h1 class = "M-TITTL">ADD CASES</h1>      
            </div>

            <form action="{{Route('front.store')}}" method="POST" enctype="multipart/form-data">
            @csrf  

                <div class ="Mid-Form"> 
                    <div class="EXSepator">
                        <div class="field">
                            <label>Case No. : </label>
                            <input type="text" @error('case_no') id="errors" @enderror  name="case_no" placeholder="EXAMPLE: P.I. No. 2023-QC-T-00" value="{{old('case_no')}}">
                            <span style="color: red;">@error('case_no') {{$message}} @enderror</span>   
                        </div> 
                        <div class="field">
                            <label>School : </label>
                            <input type="text" @error('school') id="errors" @enderror  name="school" placeholder="EXAMPLE: Hogwarts School of Magic" value="{{old('school')}}">
                            <span style="color: red;">@error('school') {{$message}} @enderror</span>   
                        </div> 
                    </div>

                    <div class="EXSepator">           
                        <div class="EXSepator">
                            <div class="field">
                                <label>Complainant First Name. : </label>
                                <input type="text" @error('complainantfname') id="errors" @enderror  name="complainantfname" placeholder="EXAMPLE: Mike" value="{{old('complainantfname')}}">
                                <span style="color: red;">@error('complainantfname') {{$message}} @enderror</span>   
                            </div> 
                            <div class="field">
                                <label>Complainant Middle Name : </label>
                                <input type="text" @error('complainantmname') id="errors" @enderror  name="complainantmname" placeholder="EXAMPLE: Wazawski" value="{{old('complainantmname')}}">
                                <span style="color: red;">@error('complainantmname') {{$message}} @enderror</span>   
                            </div>
                        </div>
                        <div class="EXSepator">
                            <div class="field">
                                <label>Complainant Last Name. : </label>
                                <input type="text" @error('complainantlname') id="errors" @enderror  name="complainantlname" placeholder="EXAMPLE: Tyson" value="{{old('complainantlname')}}">
                                <span style="color: red;">@error('complainantlname') {{$message}} @enderror</span>   
                            </div> 
                            <div class="field">
                                <label>Complainant Suffix : </label>
                                <input type="text" @error('complainantsuffix') id="errors" @enderror  name="complainantsuffix" placeholder="EXAMPLE: Jr." value="{{old('complainantsuffix')}}">
                                <span style="color: red;">@error('complainantsuffix') {{$message}} @enderror</span>   
                            </div>
                        </div>
                    </div>

                    
                    <div class="EXSepator">           
                        <div class="EXSepator">
                            <div class="field">
                                <label>Respondent First Name. : </label>
                                <input type="text" @error('respondentfname') id="errors" @enderror  name="respondentfname" placeholder="EXAMPLE: Juan" value="{{old('respondentfname')}}">
                                <span style="color: red;">@error('respondentfname') {{$message}} @enderror</span>   
                            </div> 
                            <div class="field">
                                <label>Respondent Middle Name : </label>
                                <input type="text" @error('respondentmname') id="errors" @enderror  name="respondentmname" placeholder="EXAMPLE: Bonifacio" value="{{old('respondentmname')}}">
                                <span style="color: red;">@error('respondentmname') {{$message}} @enderror</span>   
                            </div>
                        </div>
                        
                        <div class="EXSepator">
                            <div class="field">
                                <label>Respondent Last Name. : </label>
                                <input type="text" @error('respondentlname') id="errors" @enderror  name="respondentlname" placeholder="EXAMPLE: Dela Cruz" value="{{old('respondentlname')}}">
                                <span style="color: red;">@error('respondentlname') {{$message}} @enderror</span>   
                            </div> 
                            <div class="field">
                                <label>Respondent Suffix : </label>
                                <input type="text" @error('respondentsuffix') id="errors" @enderror  name="respondentsuffix" placeholder="EXAMPLE: Jr." value="{{old('respondentsuffix')}}">
                                <span style="color: red;">@error('respondentsuffix') {{$message}} @enderror</span>   
                            </div>
                        </div>
                    </div>
            
                    <div class="field">
                        <label>Date Of Action: </label>
                        <input type="date" @error('dateofactions') id="errors" @enderror  name="dateofactions"  value="{{old('dateofactions')}}">
                        <span style="color: red;">@error('dateofactions') {{$message}} @enderror</span>   
                    </div> 
                
                    <div class="field">
                        <label> LAST ACTION TAKEN </label>
                        <textarea type=" text" @error('actions') id="errors" @enderror name="actions" > {{old('actions')}} </textarea>
                        <span style="color: red;"> @error('actions') {{$message}} @enderror </span>       
                    </div> 
                
                    <div class="EXSepator">

                        <div class="field">
                            <label> CHARGES </label>
                            <textarea type=" text" @error('charges') id="errors" @enderror name="charges"> {{old('charges')}} </textarea>
                            <span style="color: red;"> @error('charges') {{$message}} @enderror </span>         
                        </div> 

                        <div class="field">
                            <label> STATUS </label>
                            <textarea type=" text" @error('status') id="errors" @enderror name="status" > {{old('status')}} </textarea>
                            <span style="color: red;"> @error('status') {{$message}} @enderror </span>         
                        </div> 
                    </div>
                    <div class="BUTNS-AD">
                        <a class ="Add-ITM-C"  href="{{Route('front.index')}}"> <i class="fa-solid fa-circle-xmark"  ></i> <span> Back </span></a>
                        <button class ="Add-ITM" type="submit"> <i class="fa-solid fa-circle-plus"></i> <span> Add </span></button>
                    </div>
                    
                    
                </div> 

            </form>

        </div> 
    </div> 
</div>

@endsection  

resources/views/TableFront/FrontTableArchives.blade.php
@extends('Layout.Layout')

@section('contents')

    
<div  class = "M-Table">
    <div class="Table-1" >
        <div class="Table-con">
            <div class="Cnt">
                <H3 class="ORPRED">PENDING INVESTIGATION : ARCHIVE </H3>
                <p class="DY">Legal and Investigation Section</p>
            </div>
            <div class = "A-DD">
                <a  href=" {{route ('front.index')}}"  class ="Add-P"> <i class="fa-solid fa-reply"></i> <span> Return </span></a> <!--Modal Button any -->
            </div> 

        </div>


        <div class = " Table-Section">
            <table id="Papers" class="display" style="width:100%">
                <thead>
                    <tr>
                        <th>CASE NO.</th> 
                        <th>SCHOOL</th>             
                        <th>COMPLAINANT</th>
                        <th>RESPONDENT</th>
                        <th>ACTIONS</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach($pendings as $pending)
                        <tr>
                            <td>{{$pending->case_no}}</td>
                            <td>{{$pending->school}}</td>
                            <td>{{$pending->complainantfname}} {{$pending->complainantmname}} {{$pending->complainantlname}} {{$pending->complainantsuffix}}</td>
                            <td>{{$pending->respondentfname}} {{$pending->respondentmname}} {{$pending->respondentlname}} {{$pending->respondentsuffix}}</td>                        
                            <td class="BTNS-EDTY">  
                                <button class="Dlts" onclick="deleteDataPermanent({{$pending->id}})" type="submit"><i class="fa-solid fa-trash"></i> <span> DELETE </span> </button>
                                    <form id ="deleteP-form-{{$pending->id}}" action="{{Route('PendingArchivesDestroy', $pending->id)}}" method = "POST"> @csrf @method('DELETE')  </form>
                                <button class="EditsT" onclick="resetData({{$pending->id}})" type="submit"><i class="fa-solid fa-repeat"></i> <span> RESTORE </span> </button> 
                                    <form id ="reset-form-{{$pending->id}}" action="{{Route('PendingArchivesStore', $pending->id)}}" method = "POST"> @csrf @method('PUT') </form>     
                            </td>
                        </tr>
                     @endforeach
                </tbody>
            </table>          
        </div>                  
    </div>
</div>
@endsection

resources/views/YouSearch.blade.php
@extends('Layout.Layout')


@section('contents')


@if(count($posts) == count($tbls))

<center>
    <form action="{{route('search')}}" method="GET">
        <div class="logo" >
             <img alt="Google" src="/AssetsIMG/sdologo.png">
        </div>
        <div class="bar">
            <input class="searchbar" type="text" title="Search" name="search">
            <button type="submit"> <img class="voice" src="https://cdn1.iconfinder.com/data/icons/hawcons/32/698627-icon-111-search-512.png" title="Search by Voice"></button>
        </div>
        <div class="buttons">
            <button class="button" type="button">LEGAL & INVESTIGATION SECTION</button>  
        </div>
    </form>

@elseif ($posts->isNotEmpty())

    <form action="{{ route('search') }}" method="GET">
      
        <div class=" gloki"> 
            <div class="bars">
                <input class="searchbars" type="text" title="Search" name="search">
                <button type="submit"> <img class="voices" src="https://cdn1.iconfinder.com/data/icons/hawcons/32/698627-icon-111-search-512.png" title="Search by Voice"></button>
            </div>
            
            <div class="logos">
               <a href="{{ route('search') }}">  <img alt="Google" src="/AssetsIMG/sdologo.png"> </a>
           </div>
        </div>
    </form>

    <div class="popcon">
        <div class="post-list">
            <p><b>Case No.</b></p>
            <p><b>School.</b></p>
            <p><b>Complainant.</b></p>
            <p><b>Respondent.</b></p>
        </div>
    </div>
    @foreach ($posts as $post)
    <div class="popcon">
        <a href="{{route('search.show',$post->id)}}" class="post-list">
            <p>{{$post->case_no}}</p>
            <p>{{$post->school}}</p>
            <p>{{$post->complainantfname}} {{$post->complainantmname}} {{$post->complainantlname}} {{$post->complainantsuffix}}</p>
            <p>{{$post->respondentfname}} {{$post->respondentmname}} {{$post->respondentlname}} {{$post->respondentsuffix}}</p>        
        </a>
    </div>
    @endforeach

    <div style="height: 300px"></div>
    <div class="whatif">
       <h3>WHO MAY FILE A COMPLAINT:</h5>
       <p class="cbs">Any person who has a cause of action may file an administrative complaint against any of the following:</p>
       <p class="cb"> <b>a.</b>  Non-teaching employee</p>
       <p class="cb"> <b>b.</b> Teaching/teaching related employee.</p> 
    </div>
    <div class="whatif">
        <h3>WHERE TO FILE</h5>
        <p class="cbsk">Complaint against non-teaching employee = <b>  Division Office. </b></p>
        <p class="cbsk">Complaint against non-teaching employee = <b>  Division Office or Regional Office. </b></p>
     </div>
     <div class="whatif">
        <h3>WHAT ARE THE REQUIREMENTS:</h5>
        <p class="cbs"> <b>1.</b> Verified Affidavit of Complaint in 4 copies containing the following:</p>
        <p class="cb"> <b>a.</b> Full name and address of the complainant</p>
        <p class="cb"> <b>b.</b> Full name and address of the person complained of, as well as his/her position and office in the Department of Education</p> 
        <p class="cb"> <b>c.</b>  Verified Affidavit of Complaint in 4 copies containing the following:</p>
        <p class="cb"> <b>d.</b> Certified true copies of documentary evidence and affidavits of his/her witnesses, if any.</p> 
        <p class="cbs"> <b>2.</b> Certificate of Non-Forum Shopping</p>
     </div>
@else
    <div style="align-items: ce">
        <h2>No posts found</h2>
    </div>
@endif

@endsection